version: 2
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
    nix:
      - image: nixos/nix:latest
jobs:
  build:
    #working_directory: /app
    executor: nix
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            nix-channel --update
            nix-env -u
            #nix-env -iA nixos.docker
      - run:
          name: Build application Docker image
          command: |
            nix-build && cp -L result app
  publish:
    executor: docker-publisher
      name: Push application Docker image
      command: |
        echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        IMAGE_TAG=${CIRCLE_TAG/v/''}
        docker tag gabysbrain-website:latest gabysbrain-website:$IMAGE_TAG
        docker push gabysbrain-website:latest
        docker push gabysbrain-website:$IMAGE_TAG
        #docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
        #docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"

workflows:
  version: 2
  build:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
