version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Record image tag
          command: |
            echo "export IMAGE_TAG=\"1.0.${CIRCLE_BUILD_NUM}\"" >> $BASH_ENV
      - run: 
          name: Build docker image
          command: docker build -t gabysbrain/website:$IMAGE_TAG .
      - run:
          name: Tag latest image
          command: |
            docker tag gabysbrain/website:$IMAGE_TAG gabysbrain/website:latest 
      - run:
          name: Login to docker hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push application docker image
          command: |
            docker push gabysbrain/website:latest
            docker push gabysbrain/website:$IMAGE_TAG

