version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
  nixos:
    docker:
      - image: nixos/nix:latest
jobs:
  build:
    executor: nixos
    steps:
      - restore_cache:
          keys:
            - nix-cache
      - checkout
      - run:
          name: Increase stack size for arguments
          command: ulimit -s 65536
      - run:
          name: Install dependencies
          command: |
            nix-channel --update
            nix-env -u
            #nix-env -iA nixos.docker
      - run:
          name: Build application Docker image
          command: |
            nix-build && cp -L result image.tar

      - save_cache:
          key: nix-cache
          paths:
            - /nix/store
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish:
    executor: docker-publisher
    steps:
      - run:
          name: Push application Docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_TAG="1.0.${CIRCLE_BUILD_NUM}"
            docker tag gabysbrain-website:latest gabysbrain-website:$IMAGE_TAG
            docker push gabysbrain-website:latest
            docker push gabysbrain-website:$IMAGE_TAG
            #docker tag app "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"
            #docker push "${ECR_ENDPOINT}/app:${CIRCLE_SHA1}"

workflows:
  build:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
