version: 2.1
executors:
  docker-publisher:
    docker:
      - image: circleci/buildpack-deps:stretch
  nixos:
    docker:
      - image: nixos/nix:latest
jobs:
  build:
    executor: nixos
    steps:
      - restore_cache:
          keys:
            - nix-cache
      - checkout
      - run:
          name: Increase stack size for arguments
          command: ulimit -s 65536
      - run:
          name: Install dependencies
          command: |
            nix-channel --update
            nix-env -u
            #nix-env -iA nixos.docker
      - run:
          name: Build application Docker image
          command: |
            ulimit -s 65536 && nix-build && cp -L result image.tar

      # TODO: clean nix directory before saving cache to keep things smaller
      - save_cache:
          key: nix-cache
          paths:
            - /nix/store
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: workspace
      - setup_remote_docker
      - run:
          name: Login to docker hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Import docker image
          command: |
            IMAGE_TAG="1.0.${CIRCLE_BUILD_NUM}"
            docker import workspace/image.tar gabysbrain/website:$IMAGE_TAG
      - run:
          name: Push application docker image
          command: |
            docker tag gabysbrain/website:$IMAGE_TAG gabysbrain/website:latest 
            docker push gabysbrain/website:latest
            docker push gabysbrain/website:$IMAGE_TAG

workflows:
  build:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
